version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ts-chat
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ts-chat
      - ENCRYPTION_KEY=password
      - NODE_ENV=production
    depends_on:
      postgres:
        condition: service_healthy
    # volumes:
    # - .:/app
    # - /app/node_modules
    command: npm run start

volumes:
  postgres_data:
